trigger: none

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the planning phase of the request."
- stage: Dev
  jobs:
  - job: Initial_Source
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the development phase of the request."
- stage: QA
  jobs:
  - job: Unit_Test
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the code deployment phase to test instance."
- stage: UAT
  jobs:
  - job: Regression_Test
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the UAT testing phase of the request."
- stage: registerArtifact
  jobs:
  - job: Register_Artifact
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev271065-Dev271065-ServiceNow DevOps Service Connection'
        artifactsPayload: |
                {"artifacts": [
                  {
                  "name": "sa-web.jar",
                  "version": "3.1",
                  "semanticVersion": "3.1.0",
                  "repositoryName": "Dev271065" 
                }]}
            
- stage: Prod
  jobs:
  - job: Final_Deployment
    pool:
      name: server
