trigger: none
pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the planning phase of the request."
- stage: Dev
  jobs:
  - job: Initial_Source
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the development phase of the request."
- stage: QA
  jobs:
  - job: Unit_Test
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the code deployment phase to test instance."
- stage: UAT
  jobs:
  - job: Regression_Test
    steps:
    - task: CmdLine@2
      inputs:
        script: echo "This is the UAT testing phase of the request."
- stage: registerArtifact
  jobs:
  - job: Register_Artifact
    pool:
      name: server
    steps:
    - task: ServiceNow-DevOps-Server-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev271065-Dev271065-ServiceNow DevOps Service Connection'
        artifactRegistrationPayload: |
          {
             "artifacts": [
                {
                   "name": "app-devops-cicd.jar",
                   "version": "1.$(build.buildId)",
                   "semanticVersion": "1.$(build.buildId).0",
                   "repositoryName": "regArtifact"
             "pipelineName": "$(system.teamProject)/$(build.definitionName)",
             "taskExecutionNumber": "$(build.buildId)",
             "stageName": "$(system.jobDisplayName)",
           "attemptNumber": "$(system.jobAttempt)",
             "branchName": "$(build.sourceBranchName)"
          }
        artifactToolIdExists: true
- stage: registerPackage
  jobs:
  - job: Register_Package
    pool:
      name: server
    steps:
    - task: ServiceNow-DevOps-Server-Package-Registration@1
      inputs:
        connectedServiceName: 'dev271065-Dev271065-ServiceNow DevOps Service Connection'
        packageRegistrationPayload: |
          {
              "name": "app-devops-change-velocity-cicd.war",
              "artifacts": [
              {
                  "name": "app-devops-cicd.jar",
                  "repositoryName": "npj96/NJ-DemoRepo",
                  "version": "1.$(build.buildId)",
                  "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber":"$(build.buildId)",
                  "stageName":"$(system.jobDisplayName)",
            "attemptNumber":"$(system.jobAttempt)",
                "branchName":"$(build.sourceBranchName)"
              }],
              "pipelineName":"$(system.teamProject)/$(build.definitionName)",
              "taskExecutionNumber":"$(build.buildId)",
              "stageName":"$(system.jobDisplayName)",
           "attemptNumber":"$(system.jobAttempt)",
              "branchName":"$(build.sourceBranchName)"
          }
        artifactToolIdExists: true
- stage: Prod
  jobs:
  - job: Final_Deployment
    pool:
      name: server